### ISSUE TITLE
ImportError: cannot import name '_Seq2SeqWrapper' from 'allennlp.modules.seq2seq_encoders'

### ISSUE THREAD

**Issue by mayhewsw** [allenai/allennlp-server#7]
In a clean conda environment (python 3.7), I did:
```bash 
$ git clone https://github.com/allenai/allennlp
$ cd allennlp
$ pip install --editable .
$ git clone https://github.com/allenai/allennlp-server
$ cd ../allennlp-server
$ pip install --editable .
$ allennlp serve -h
```

This gives me an error: 
```
ImportError: cannot import name '_Seq2SeqWrapper' from 'allennlp.modules.seq2seq_encoders'
```

Possible issues:
* Needs to be a pip environment?
* A specific version of AllenNLP is required?

**Comment by bryant1410** [comment]
It should work from master. I'm getting the same error with master to me too yeah (not with a previous version). I got:

```
$ allennlp serve -h
2020-02-11 14:37:14,303 - INFO - transformers.file_utils - PyTorch version 1.4.0 available.
Traceback (most recent call last):
  File "/home/sacastro/.pyenv/versions/allennlp-server/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/sacastro/.pyenv/versions/3.7.6/envs/allennlp-server/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/sacastro/.pyenv/versions/3.7.6/envs/allennlp-server/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 82, in main
    import_plugins()
  File "/home/sacastro/.pyenv/versions/3.7.6/envs/allennlp-server/lib/python3.7/site-packages/allennlp/common/plugins.py", line 80, in import_plugins
    importlib.import_module(module_name)
  File "/home/sacastro/.pyenv/versions/3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/s/repos/allennlp-server/allennlp_plugins/allennlp_server/__init__.py", line 1, in <module>
    import allennlp_server
  File "/s/repos/allennlp-server/allennlp_server/__init__.py", line 1, in <module>
    import allennlp_server.commands
  File "/s/repos/allennlp-server/allennlp_server/commands/__init__.py", line 1, in <module>
    from allennlp_server.commands.configure import Configure
  File "/s/repos/allennlp-server/allennlp_server/commands/configure.py", line 24, in <module>
    from allennlp_server.config_explorer import make_app
  File "/s/repos/allennlp-server/allennlp_server/config_explorer/__init__.py", line 1, in <module>
    from allennlp_server.config_explorer.config_explorer import make_app
  File "/s/repos/allennlp-server/allennlp_server/config_explorer/config_explorer.py", line 11, in <module>
    from allennlp_server.config_explorer.configuration import choices, configure
  File "/s/repos/allennlp-server/allennlp_server/config_explorer/configuration.py", line 29, in <module>
    from allennlp.modules.seq2seq_encoders import _Seq2SeqWrapper
ImportError: cannot import name '_Seq2SeqWrapper' from 'allennlp.modules.seq2seq_encoders' (/home/sacastro/.pyenv/versions/3.7.6/envs/allennlp-server/lib/python3.7/site-packages/allennlp/modules/seq2seq_encoders/__init__.py)
```

**Comment by bryant1410** [comment]
Probably it's broken by allenai/allennlp#3740

I wonder if the plugin import should catch any exception, not just import exceptions.

**Comment by bryant1410** [comment]
@mayhewsw #8 fix it. You can check out that branch and install it while it's not in master.
